# Generated by Django 3.0.5 on 2020-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlgym1', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=200, upload_to='uploads/'),
        ),
    ]
