# Generated by Django 3.0.5 on 2020-04-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlgym1', '0004_auto_20200422_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThetaString',
        ),
    ]
